# permissions to do viewer breads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bread-viewer-role
rules:
- apiGroups:
  - core.run-linux.com
  resources:
  - breads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.run-linux.com
  resources:
  - breads/status
  verbs:
  - get
