# permissions to do edit breads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bread-editor-role
rules:
- apiGroups:
  - core.run-linux.com
  resources:
  - breads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.run-linux.com
  resources:
  - breads/status
  verbs:
  - get
  - patch
  - update
